---
abstract: 'PerlTidy in Dist::Zilla'
author:
  - 'Fayland Lam <fayland@gmail.com>'
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-PerlTidy
requires:
  Dist::Zilla: 2.100880
  File::Copy: 0
  File::Next: 0
  Perl::Tidy: 0
resources:
  repository: git://github.com/fayland/dist-zilla-plugin-perltidy.git
version: 0.11
